---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/expenses":
    get:
      summary: list expenses
      parameters:
      - name: date
        in: query
        schema:
          type: string
        required: false
      - name: year
        in: query
        schema:
          type: string
        required: false
      - name: month
        in: query
        schema:
          type: string
        required: false
      - name: date_two
        in: query
        schema:
          type: string
        required: false
      responses:
        '200':
          description: list of expenses
    post:
      summary: create expense
      parameters: []
      responses:
        '200':
          description: expense created
        There was an error in the parameters:
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                payee:
                  type: string
                amount:
                  type: number
                  multipleOf: 0.01
                expense_date:
                  type: string
              required:
              - payee
              - amount
              - expense_date
  "/api/v1/expenses/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show expense
      responses:
        '200':
          description: successful
    patch:
      summary: update expense
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                payee:
                  type: string
                amount:
                  type: number
                  multipleOf: 0.01
                expense_date:
                  type: string
    delete:
      summary: delete expense
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
